import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import {chillax} from '@/styles/fonts'
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          chillax.variable,
          "font-sans", 
          " text-black min-h-screen w-screen transition-colors duration-500 overflow-x-hidden"
        )}
      >
        {children}
        <Toaster />

      </body>
    </html>
  );
}
